name: tile_two
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flame: ^1.11.0 # Core Flame Engine
  flame_svg: ^1.10.0 # For SVG assets
  flutter_svg: ^2.0.9
  http: ^1.2.2
  shared_preferences: ^2.3.2
  flame_audio: ^2.10.8
  google_mobile_ads: ^7.0.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/icon_launcher.png
  adaptive_icon_foreground: assets/images/icon_launcher.png
  adaptive_icon_background: "#101010"
  adaptive_icon_foreground_inset: 22

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/sprite/
    - assets/audio/
    - assets/l10n/

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_logo.jpg
  android: true
  ios: true
  fullscreen: true

